# docker service rm ocelot_bakery_api || true && docker stack deploy -c $(pwd)/api.yaml --resolve-image=never ocelot_bakery

version: '3.7'

services:

  api:
    image: lanl0rd/js
    networks:
      - network_overlay
    volumes:
      - ../../../:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.ocelot_bakery_api.rule=Host(`bakery-api.ocelot.work`)
        - traefik.http.services.ocelot_bakery_api.loadbalancer.server.port=3000
        - traefik.http.services.ocelot_bakery_api.loadbalancer.sticky.cookie.name=sticky
        - traefik.http.services.ocelot_bakery_api.loadbalancer.sticky.cookie.secure=true
        - traefik.http.services.ocelot_bakery_api.loadbalancer.sticky.cookie.httpOnly=true
    working_dir: /app
    ports:
      - "3000:3000"
    command: nx serve bakery-api

networks:
  network_overlay:
    external: true