# docker service rm ocelot_dev_face || true && docker stack deploy -c $(pwd)/face.yaml --resolve-image=never ocelot_dev

version: '3.7'

services:

  face:
    image: lanl0rd/face
    environment:
      - HTTP_PASSWORD=$HTTP_PASSWORD
    networks:
      - network_overlay
    ports:
      - "8008:80"
      - "5090"
    volumes:
      - ../../../:/root/ocelot
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  network_overlay:
    external: true