# docker service rm ocelot_bakery-api || true && docker service rm ocelot_bakery || true && docker stack deploy -c $(pwd)/bakery.yaml --resolve-image=never ocelot

version: '3.7'

services:

  bakery:
    image: lanl0rd/js
    networks:
      - network_overlay
    volumes:
      - ../../:/app
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    working_dir: /app
    ports:
      - "4200:4200"
    command: nx serve bakery --host 0.0.0.0 --disableHostCheck

  bakery-api:
    image: lanl0rd/js
    networks:
      - network_overlay
    volumes:
      - ../../:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.http.routers.ocelot_bakery-api.rule=Host(`api.bakery.work`)
        - traefik.http.services.ocelot_bakery-api.loadbalancer.server.port=3000
        - traefik.http.services.ocelot_bakery-api.loadbalancer.sticky.cookie.name=sticky
        - traefik.http.services.ocelot_bakery-api.loadbalancer.sticky.cookie.secure=true
        - traefik.http.services.ocelot_bakery-api.loadbalancer.sticky.cookie.httpOnly=true
    working_dir: /app
    ports:
      - "3000:3000"
    command: nx serve bakery-api

networks:
  network_overlay:
    external: true