# docker service rm ocelot_dev || true && docker service rm ocelot_dev || true && docker stack deploy -c $(pwd)/dev.yaml --resolve-image=never ocelot

version: '3.7'

services:

  dev:
    image: lanl0rd/face
    environment:
      - HTTP_PASSWORD=ocelot
    networks:
      - network_overlay
      - host
    ports:
      - "80"
      - "5090"
    volumes:
      - ../../certbot:/root/ocelot

networks:
  network_overlay:
    external: true